<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	 <GenerateDocumentationFile>true</GenerateDocumentationFile>
  <NoWarn>1591</NoWarn> <!-- Suppresses warnings for missing XML comments -->
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="EmployeeManagement.Models\**" />
    <Compile Remove="EmployeeManagement.MVC.Tests\**" />
    <Compile Remove="EmployeeManagement.MVC\**" />
    <Compile Remove="EmployeeManagementTests\**" />
    <Compile Remove="wwwroot\**" />
    <Content Remove="EmployeeManagement.Models\**" />
    <Content Remove="EmployeeManagement.MVC.Tests\**" />
    <Content Remove="EmployeeManagement.MVC\**" />
    <Content Remove="EmployeeManagementTests\**" />
    <Content Remove="wwwroot\**" />
    <EmbeddedResource Remove="EmployeeManagement.Models\**" />
    <EmbeddedResource Remove="EmployeeManagement.MVC.Tests\**" />
    <EmbeddedResource Remove="EmployeeManagement.MVC\**" />
    <EmbeddedResource Remove="EmployeeManagementTests\**" />
    <EmbeddedResource Remove="wwwroot\**" />
    <None Remove="EmployeeManagement.Models\**" />
    <None Remove="EmployeeManagement.MVC.Tests\**" />
    <None Remove="EmployeeManagement.MVC\**" />
    <None Remove="EmployeeManagementTests\**" />
    <None Remove="wwwroot\**" />
     <Compile Remove="../EmployeeManagement.Mvc/**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="EmployeeManagement.Models\EmployeeManagement.Models.csproj" />
  </ItemGroup>

</Project>
