// <auto-generated />
using System;
using EmployeeManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250826112543_SeedSkills")]
    partial class SeedSkills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("EmployeeManagement.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 26, 11, 25, 43, 33, DateTimeKind.Utc).AddTicks(8191),
                            Description = "Programming in C#",
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 26, 11, 25, 43, 33, DateTimeKind.Utc).AddTicks(8422),
                            Description = "Database querying and design",
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 26, 11, 25, 43, 33, DateTimeKind.Utc).AddTicks(8424),
                            Description = "Frontend and backend scripting",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 26, 11, 25, 43, 33, DateTimeKind.Utc).AddTicks(8425),
                            Description = "Agile and Scrum methodologies",
                            Name = "Project Management"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 26, 11, 25, 43, 33, DateTimeKind.Utc).AddTicks(8426),
                            Description = "Azure and AWS services",
                            Name = "Cloud Computing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
